//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DSParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DSParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IDSParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DSParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DSParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] DSParser.If_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] DSParser.While_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.jump_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_stmt([NotNull] DSParser.Jump_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.label_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_decl([NotNull] DSParser.Label_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.dialogue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDialogue_stmt([NotNull] DSParser.Dialogue_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_stmt([NotNull] DSParser.Call_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CallCustomCommand</c>
	/// labeled alternative in <see cref="DSParser.call_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallCustomCommand([NotNull] DSParser.CallCustomCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PlayCommand</c>
	/// labeled alternative in <see cref="DSParser.call_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayCommand([NotNull] DSParser.PlayCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HideCommand</c>
	/// labeled alternative in <see cref="DSParser.call_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHideCommand([NotNull] DSParser.HideCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ShowCommand</c>
	/// labeled alternative in <see cref="DSParser.call_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShowCommand([NotNull] DSParser.ShowCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WaitCommand</c>
	/// labeled alternative in <see cref="DSParser.call_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitCommand([NotNull] DSParser.WaitCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.call_arg_pos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_arg_pos([NotNull] DSParser.Call_arg_posContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.call_arg_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_arg_key([NotNull] DSParser.Call_arg_keyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.menu_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenu_stmt([NotNull] DSParser.Menu_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.menu_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMenu_item([NotNull] DSParser.Menu_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.assignment_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_stmt([NotNull] DSParser.Assignment_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DSParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.logical_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_and([NotNull] DSParser.Logical_andContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality([NotNull] DSParser.EqualityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] DSParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] DSParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] DSParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary([NotNull] DSParser.UnaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] DSParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] DSParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DSParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] DSParser.LiteralContext context);
}
